global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "identity-player"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "matchmaking"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: "economy-community"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8083"]
